### ISSUE TITLE
Thread-Safety of fields

### ISSUE THREAD

**Issue by austinbhale** [Nakamir-Code/SKAzureCloud#1]
References to objects with read/writes in different threads could result in an old read from memory, aka a potential memory access violation. For a high-level description of this context switch, here's a good example example: https://stackoverflow.com/a/58486153. 

In this case, ‘menuState’ and ‘_resultText’ are written to from background threads and read from the game thread. What if the game thread reads an old reference that has been collected by the GC? I think we should either declare these variables as 'volatile', specify a lock, or another solution from the C# Interlocked class. Though volatile is unoptimized, it would be the easiest to implement for this short example and not matter much in terms of performance.

**Comment by Abdul-Mukit** [comment]
Thanks. Will be sure to factor them in during production code.

**Comment by austinbhale** [comment]
Code for `menuState` by using the Interlocked class:
```
private static MenuState State
{
    get { return (MenuState)Interlocked.CompareExchange(ref state, 0, 0); }
    set { Interlocked.Exchange(ref state, (int)value); }
}
private static int state = 0;
```

Then you'd refer to the enum by only getting and setting `State`

**Comment by Abdul-Mukit** [comment]
@austinbhale Do we still need the Interlocked menustate?
