### ISSUE TITLE
ConfigureAwait(false) explanation

### ISSUE THREAD

**Issue by austinbhale** [Nakamir-Code/SKAzureCloud#2]
I think we should be consistent with ConfigureAwait(false) if we are using it to see any sort of micro optimization. For example, let's use it here too: https://github.com/Nakamir-Code/AzureStereoKitUWPSamples/blob/225ab85070422f0becb0516d8c6ef5252c81a4a3/AzureStereoKitSamples/Program.cs#L267

Also, this comment makes it sound like we should use ConfigureAwait(false) whenever we are not on the UI thread, but this is not the case:

https://github.com/Nakamir-Code/AzureStereoKitUWPSamples/blob/225ab85070422f0becb0516d8c6ef5252c81a4a3/AzureStereoKitSamples/Program.cs#L259

It is generally recommended to use the default await behavior for application code and use ConfigureAwait(false) for library code since it does not care about the caller's current context. We are using ConfigureAwait(false) in our scenario because we want to use any available thread for Azure communication, as we do not care about its context on the UI thread. We just want the Azure task to complete and return data that will be consumed on any available background thread.

**Comment by austinbhale** [comment]
I really like this short video summary for understanding ConfigureAwait(false): https://youtu.be/avhLfcgIwbg

**Comment by Abdul-Mukit** [comment]
Thank you, I'll look into it.
